---
title: Cuatro Consultants
timezone: UTC
collections:
  associates:
    title: Associates
    output: true
  employees:
    title: Employees
    output: false
  master-plan-rural-projects:
    title: Master Plan Rural Projects
    output: true
    project_list: true
    image: ''
  master-plan-urban-projects:
    title: Master Plan Urban Projects
    output: false
    project_list: true
  multi-family-residential-projects:
    title: Multi Family Residential Projects
    output: true
    project_list: true
    image: ''
  posts:
    title: Posts
    output: true
  public-works-projects:
    title: Public Works Projects
    output: true
    project_list: true
    image: ''
  site-development-projects:
    title: Site Development Projects
    output: true
    project_list: true
    image: ''
  storage-facility-projects:
    title: Storage Facility Projects
    output: true
    project_list: true
    image: ''
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
Description: Cuatro Consultants, Ltd. is a civil engineering/consulting Firm offering
  a full range of design, permitting, and land development services throughout the
  Austin metropolitan and Central Texas area.  We serve a diverse Clientele ranging
  from individuals and small local companies to large national corporations.  We assist
  our Clients through all phases of their Projects, starting with concept development
  and ending with construction completion.
permalink: pretty
Email: cuatro@cuatroconsultants.com
Phone: "(512) 312-5040"
Fax: 
Address: |-
  3601 Kyle Crossing, Suite A
  Kyle, Texas 78640
markdown: kramdown
kramdown:
  hard_wrap: false
logo: "/uploads/logo.png"
icon: "/uploads/favicon.ico"
hero:
- assets/images/hero/hero1.png
- assets/images/hero/hero2.png
- assets/images/hero/hero3.png
- assets/images/hero/hero4.png
plugins:
- jekyll-remote-theme
remote_theme: thegoobs/cuatro-theme
