---
title: Cuatro Consultants
timezone: UTC
collections:
  associates:
    title: Associates
    output: true
  employees:
    title: Employees
    output: false
  multi-family-residential-projects:
    title: Multi Family Residential Projects
    output: true
  posts:
    title: Posts
    output: true
  public-works-projects:
    title: Public Works Projects
    output: true
  rural-projects:
    title: Rural Projects
    output: true
  site-development-projects:
    title: Site Development Projects
    output: true
  storage-facility-projects:
    title: Storage Facility Projects
    output: true
  uploads:
    title: Uploads
    output: true
  projects:
    title: Urban Projects
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
Email: cuatro@cuatroconsultants.com
Phone: "(512) 312-5040"
Fax: "(512) 312-5399"
Address: |-
  3601 Kyle Crossing
  Kyle, Texas 78640
