---
title: Cuatro Consultants
timezone: America/Chicago
collections:
  associates:
    title: Associates
    output: true
  employees:
    title: Employees
    output: false
  master-plan-rural-projects:
    title: Master Plan Rural Projects
    output: true
    project_list: true
    image: ''
  master-plan-urban-projects:
    title: Master Plan Urban Projects
    output: false
    project_list: true
  multi-family-residential-projects:
    title: Multi Family Residential Projects
    output: true
    project_list: true
    image: ''
  posts:
    title: Posts
    output: true
  public-works-projects:
    title: Public Works Projects
    output: true
    project_list: true
    image: ''
  services:
    title: Services
    output: true
  site-development-projects:
    title: Site Development Projects
    output: true
    project_list: true
    image: ''
  storage-facility-projects:
    title: Storage Facility Projects
    output: true
    project_list: true
    image: ''
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
Description: Cuatro Consultants, Ltd. is a civil engineering and consulting engineering
  firm offering full range land entitlement services, including master planning, preliminary
  plans, final plats, site development permit plans, and feasibility/due diligence
  studies throughout the Central and West Texas area.  We serve diverse Clientele
  ranging from individual landowners and local companies to national corporations.  We
  assist our Client through all phases of the Project, starting with concept development
  and ending with construction completion.
permalink: pretty
Email: cuatro@cuatroconsultants.com
Phone: "(512) 312-5040"
Address: |-
  120 Riverwalk Drive, Suite 208
  San Marcos, Texas 78666
markdown: kramdown
kramdown:
  hard_wrap: false
logo: "/uploads/NEW%20CUATRO%20LOGO.png"
icon: "/uploads/favicon.ico"
hero:
- assets/images/hero/hero1.png
- assets/images/hero/hero2.png
- assets/images/hero/hero3.png
- assets/images/hero/hero4.png
plugins:
- jekyll-remote-theme
remote_theme: thegoobs/cuatro-theme
